### ISSUE TITLE
[Request] Increase blur on wallpaper

### ISSUE THREAD

**Issue by phampyk** [Anthonyy232/Paperize#103]
Hello! Thank you for the app, it's great and so much nicer on the battery than Muzei. 

I would like to ask if it could be possible to increase the blur on the wallpaper. I love that you can choose different blur between lockscreen and main screen, but when I've got wallpapers that are busy or with text, it makes the icon's labels on the main screen less visible, so it would be amazing the possibility of adding more blur to it.

Thank you!

**Comment by Anthonyy232** [comment]
To clarify, your feature request is to increase the blur strength? So 100% should be stronger than what 100% is currently? 

Will do!

**Comment by phampyk** [comment]
> To clarify, your feature request is to increase the blur strength? So 100% should be stronger than what 100% is currently?
> 
> Will do!

Yes! That's exactly it. Thank you!!

**Comment by Anthonyy232** [comment]
Fixed in commit https://github.com/Anthonyy232/Paperize/commit/9563bf205740ce5b22239710c9d3dac6ae1f7b64
