### ISSUE TITLE
option to change wallpaper at a set time

### ISSUE THREAD

**Issue by HypNotiQ4** [Anthonyy232/Paperize#118]
Not really an issue, more of a suggestion
But being able to have it change at a specific time (1am every day for example) would be dope

**Comment by Anthonyy232** [comment]
Hi, thank you for your suggestion! I apologize, but I won't be adding this. A goal I always wanted for this app was to keep it simple, and I just don't feel like complicating the app more than necessary. 

This is obviously not as nice, but you could probably change your device system time and then schedule the wallpaper changer for 24 hours -- or just stay up till 1 AM and enable it.
