### ISSUE TITLE
[BUG] Wallpaper changes incorrectly when in horizontal orientation

### ISSUE THREAD

**Issue by sakarie9** [Anthonyy232/Paperize#119]
![image](https://github.com/user-attachments/assets/d3ddd711-207b-4efd-bf5a-d32baa4f6a6c)

Left: Normal | Right: Issue

The image on the left shows the expected behavior, while the image on the right demonstrates the issue. This bug can be reproduced with any image.

- How to reproduce
  - Add the "Change Wallpaper" tile to Quick Settings.
  - Open an app that forces the phone into horizontal orientation, such as a fullscreen YouTube video.
  - While the phone is in horizontal orientation, tap the "Change Wallpaper" tile from Quick Settings.
  - Wait a few seconds to ensure the wallpaper has changed.

The previous steps are meant to ensure that the phone is in horizontal orientation when the wallpaper changes, whether triggered by a timer or manually.

**Comment by Anthonyy232** [comment]
Fixed in commit https://github.com/Anthonyy232/Paperize/commit/5a1f11ba4f2fc73e396e9aa71817a10f78b6c748
