### ISSUE TITLE
[Feature request] Add option to set home screen wallpaper darkening \ dimming 

### ISSUE THREAD

**Issue by M7amma** [Anthonyy232/Paperize#121]
Today I discovered this awesome app and I'm really astonished by the modernism and functionality. Such app is essential for me because sticking with a single wallpaper makes the phone usability very boring for me. So thank you so much for making this awesome and neat app. 

I came here wondering if it possible to add option called 'Darken \ dim wallpaper'. To better explain it, I'll attach a screenshot of this option from an app called _wallpaper changer _ that I immediately abandoned after the discovery of **Paperize**. The option will basically add a dark layer on the main screen wallpaper making it less brighty. There's also that dimming valuse % that should be also considered. ![Screenshot_20240905-064515_Wallpaper Changer.png](https://github.com/user-attachments/assets/4680f76f-a430-4568-99a1-0a1bae83766a)

_Note : No need to apply it for lock screen, only the home screen wallpaper would be enough _

**Comment by Anthonyy232** [comment]
Correct me if I'm wrong, but is this not the same thing?

![image](https://github.com/user-attachments/assets/0ec3649f-38c1-49b5-a870-a8908e1b1134)

**Comment by M7amma** [comment]
Great! So the option is there but I didn't notice it! I tested it and the effect is the same 🤝😄 thanks and no need to add anything new
