### ISSUE TITLE
Change album as per location/time set

### ISSUE THREAD

**Issue by Murti53** [Anthonyy232/Paperize#131]
Hi,

Is it possible to trigger an album when you are at a specific location and once you are out of that location, it changes to a different set album? Also an option to set time for a specific album to trigger?

I could see there is a tasker integration but i could not use the paperize plugin while creating a task in tasker. I am not able to change the configuration (screenshot attached). 

Please let me know if you need any more info.

Loving the app so far!

[Screenshot_2024-09-05-18-51-07-71_78c564e752295d769e9a0ddd26e8199d.jpg](https://github.com/user-attachments/assets/e94bc418-61cd-4868-a37c-a27d83d77d1e)

**Comment by Anthonyy232** [comment]
I don't think I will add this, but I will look into fixing the tasker integration. Do you think you could post a step-by-step or a video on how to set up the tasker integration? I have the app but have never used it, and the UI is quite confusing.

**Comment by Murti53** [comment]
I can try and send you a step by step tutorial in a word file or something.. will it be okay?

**Comment by Anthonyy232** [comment]
Yeah sure

**Comment by Anthonyy232** [comment]
Fixed the tasker integration in commit https://github.com/Anthonyy232/Paperize/commit/58c35c1bbbce5284baa3899bf08031224aee069a

Will create a new release soon

**Comment by Murti53** [comment]
Thank you for the fix. It was around 3 am my time so i couldn't send the instructions for tasker. But glad you were able to fix it.

**Comment by Anthonyy232** [comment]
Sure. I checked it on my mind, but please confirm that it works. Thanks!

**Comment by Murti53** [comment]
![Screenshot_2024-09-06-14-09-10-57_78c564e752295d769e9a0ddd26e8199d.jpg](https://github.com/user-attachments/assets/c25172e9-9476-4b66-8c90-44306802a348)

I checked and it is working. But instead of changing the wallpaper, can you add selecting the album? So i can bind the task with a location in the tasker. And once i reach that location the task will get activated and will select the album created in paperize.

**Comment by Murti53** [comment]
Hi .. Is it possible to add the album option in tasker instead of adding the wallpaper?

**Comment by Anthonyy232** [comment]
I saw your previous comment. I don't know -- I'll have to see if it is possible and how feasible it is when I get the time. Been busy with school work and job search (I'm a student) so haven't had a chance to implement new features

**Comment by Murti53** [comment]
It's okay.. Take your time. And good luck for finding the job..!! ✌️
