### ISSUE TITLE
[Feature request] Update option on the app

### ISSUE THREAD

**Issue by ugurkuyu** [Anthonyy232/Paperize#137]
It would be great if there was an update option on the app. It is quite bothersome to check the github repo every time. Thanks in advance

**Comment by Anthonyy232** [comment]
Hi! You can download from F-Droid or IzzyOnDroid and it should auto-update I think. Probably won't implement this as a "goal" of the app is to be completely offline and doesn't connect to the internet and this would require reading data from online.
