### ISSUE TITLE
[Feature request] <
Remove Next  Wallpaper Change notification> 

### ISSUE THREAD

**Issue by Ansarmughal99** [Anthonyy232/Paperize#138]
Every time when the wallpaper changes there is notification for the upcoming wallpaper which is annoying .

There should be at least a setting to allow notification for the wallpaper Change 

I hate to Swipe notification every time .
 
I have attached the screenshot 
I love this wallpaper![IMG_20240908_163158.jpg](https://github.com/user-attachments/assets/344e9118-5dfc-4452-81b8-c4588d06e93b)

**Comment by Anthonyy232** [comment]
Closing as disabling notifications is a basic Android feature..

**Comment by Anthonyy232** [comment]
https://github.com/user-attachments/assets/f6ea4cc5-730d-4d64-814b-b1bd7959575d
