### ISSUE TITLE
[Feature request] Optionally stop automatic wallpaper change.

### ISSUE THREAD

**Issue by M7amma** [Anthonyy232/Paperize#152]
Please add option to stop changing the wallpaper automatically. I would like to use this app without any automated tasks i.e changing wallpaper on time interval. I already use it now by triggering the wallpaper change manually by a gesture on my home screen using the triggering 'acticity' method. Thank you.

**Comment by Anthonyy232** [comment]
This might actually be quite easy for me to implement, and I think I can do it this way too. Currently, turning off the toggle disables any possibility of changing wallpaper. However, I may consider changing to so it only disables the automatic part.

**Comment by M7amma** [comment]
> This might actually be quite easy for me to implement, and I think I can do it this way too since it may make more sense. Currently, turning off the toggle disables any possibility of changing wallpaper. However, I may consider changing to so it only disables the automatic part.

Exactly. Thank you so much.

**Comment by Anthonyy232** [comment]
Added in commit https://github.com/Anthonyy232/Paperize/commit/bdd89a27b9c46dda03df3eb9f3a157a2c9c1e34b
