### ISSUE TITLE
[Feature request] Possible to add video wallpaper support?

### ISSUE THREAD

**Issue by M7amma** [Anthonyy232/Paperize#153]
Like if we have an album mix of images and videos, the app will be able to set each type of them as home screen wallpaper and lock screen also.
Video extension support initially would be .mp4 and .mov 😍

**Comment by Anthonyy232** [comment]
Sorry, not possible until Android/Google starts putting some work into the API again. This is only possible with the live wallpaper method, which this app does not use (for battery reasons).
