### ISSUE TITLE
[Bug] Wallpaper Resized too big when watching videos

### ISSUE THREAD

**Issue by WVoss31** [Anthonyy232/Paperize#154]
**Describe the bug**
When watching videos on my pixel 7 pro, and entering full screen viewing mode, if a wallpaper switch occurs during that time, the wallpaper image will be scaled massively and not in portrait mode. This issue affects both home and lock screens.

**To Reproduce**
1. Turn off auto rotate
2. Go to youtube (or any video platform that allows to view in fullscreen)
3. Watch video in full screen, while also having the wallpaper switch
4. exit video app and see formatting issue with wallpaper

**Expected behavior**
I expected the wallpaper to switch normally and not be super enlarged.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 14
 - Version Can't find full version number, but its the newest update from google

**Additional context**
Bitmap mode is set to fill in the app. 
Animation setting is also on in the app.

I believe that whatever logic you may be using to grab screen size is flawed, causing the image to either scale way out of proportion or reset to some default size. I might also have a look in the code to see anything else I can find.

**Comment by Anthonyy232** [comment]
I'll have a look at this. Can you confirm/deny that it occurs when in other video players?

**Comment by WVoss31** [comment]
> I'll have a look at this. Can you confirm/deny that it occurs when in other video players?

100% can confirm. Happens in browser as well as regular video apps.

**Comment by WVoss31** [comment]
I also updated the original post to include some extra info.

Bitmap mode is set to fill in the app.
Animation setting is also on in the app.

**Comment by WVoss31** [comment]
![bug](https://github.com/user-attachments/assets/6ff22c72-29e8-4ded-bc74-195fefa23e38)

I think I found the bug. When the wallpaper changes in the video player, it recognizes the screen orientation to be horizontal, and sets the wallpaper to be horizontal. However, due to having auto rotate off, when I exit the video player it puts me back into portrait mode, with the image still being the size of when my screen was horizontal. This means that the image is stuck with the wrong proportions until the next wallpaper is changed, where the app re -grabs the screen dimensions.

**Comment by Anthonyy232** [comment]
I'm not able to replicate this. Can you provide your wallpaper?

**Comment by WVoss31** [comment]
It has happened with multiple wallpapers. Did you make sure auto rotate was off? I will try to install Java 8 and build it to see if I can reproduce it in the emulator for you.

**Comment by Anthonyy232** [comment]
Is this the correct way to do it? Tried it on the emulator and also my S24U

Uploading Screen_Recording_20240918_115505_YouTube.mp4…

**Comment by WVoss31** [comment]
I tried reproducing it, but it no longer works. I did update paperize to the newest version when it was available from F Droid, so that might have fixed it? I am going to close this for now, but I might re open if I notice this issue again

**Comment by Anthonyy232** [comment]
Sure, let me know if it occurs again. As an FYI, F-Droid builds their own apk which has around a week delay, so any updates here will take a bit to reflect there.
