### ISSUE TITLE
[Bug] Monet color stops working after wallpaper change

### ISSUE THREAD

**Issue by M7amma** [Anthonyy232/Paperize#173]
**Describe the bug**
When I change the wallpaper with Paperize the system monet color doesn't change with it. But sometimes the system monet color comply with the wallpaper color but only after system/ui restart. Can we fix this behavior and make the monet color of the system comply to the wallpaper color instantly after changing the wallpaper? 

**To Reproduce**

**Expected behavior**
The system monet color should respect the wallpaper color but it doesn't

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Xiaomi X5 Pro 5G spoofed as pixel9.
 - OS: AOSP based rom InfinityX 1.5
 - Version [e.g. v2.1.1]

**Additional context**

**Comment by Anthonyy232** [comment]
Can you clarify what settings in the app you used?

**Comment by Anthonyy232** [comment]
It seems to work on my Android Studio Pixel emulator, so I'm not really sure what the issue is -- unless I can get more information. If I had to guess, it may just be that your custom ROM doesn't correctly implement the Monet engine. Let me know the settings you used so I can check how it responds with those exact same settings on my emulator. If you want, you can also provide the wallpaper you used.

**Comment by M7amma** [comment]
Sorry for coming back very late. 
So here is my preferences in the app

![Screenshot_20240929-103000_Paperize.png](https://github.com/user-attachments/assets/73a6555f-e27b-40cb-8aa3-3a1974277c04)

I actually set the app to change the wallpaper by pressing on the quick settings tile that's provided by Paperize. And here is a screen record of the actions I make
https://imgur.com/a/Y7LeqMq
The expected behavior is the background color of the qs tile changes by wallpaper change but it is not. Although when I change the wallpaper manually from the gallery, the monet engine changes the qs tiles area instantly

**Comment by Anthonyy232** [comment]
https://github.com/user-attachments/assets/9789586e-735b-43e6-817b-d19d8f16f321

As seen here, the behavior is pretty poorly implemented by Google. To be clear, I nor any other wallpaper apps have access to the ability to change the dynamic theming -- it is 100% on the OEM software. Sorry that I can't be much more help but that's how it is.
