### ISSUE TITLE
[Feature request] Add backdrop synchronization 

### ISSUE THREAD

**Issue by Tecnologiko** [Anthonyy232/Paperize#176]
Please add the ability to sync favorite backdrops like munzei without having to have it in the

**Comment by Anthonyy232** [comment]
Can you clarify what you mean? I've got no clue

**Comment by sahishnu111** [comment]
@Anthonyy232 i really like this feature added to the app and i'd love to contribute to this feature! 


i think this can be implement using a syncing mechanism that will store and sync users' favorite backdrops across devices, without needing them to be stored locally on the device. i'm thinking of using a cloud-based solution (e.g., Firebase or another cloud service) to handle the backdrop metadata, which would allow seamless access to backdrops from anywhere. or could be another similar solution 


Rough sketch of thinking: 


- Add a feature for users to mark backdrops as favorites. 


- Store favorite backdrops in a cloud service, which will sync them across devices. 


- Add UI options in the app for managing and syncing favorites. 


- Use a background service to automatically sync backdrops periodically or on user request. 


i am considering the this approach i would love to hearing from you i am new to this community love to contribute and working with you.

**Comment by sahishnu111** [comment]
@Anthonyy232 i think @Tecnologiko is talking about the feature where When a user selects or marks a backdrop (wallpaper) as a favorite, the app will store this selection on a cloud server (or similar backend).
The idea is that the user’s favorite backdrops won’t just be stored locally on the device, but instead, they can be accessed and applied on any device the user logs into.

**Comment by Anthonyy232** [comment]
Hi, I'm not willing to add this feature currently as I'd like the app to remain completely on-device. However, I may reconsider in the future or you (or someone else!) may fork the project and add it :)
