### ISSUE TITLE
[Feature request] Ability to set the Change Time

### ISSUE THREAD

**Issue by Wrakor** [Anthonyy232/Paperize#179]
**Is your feature request related to a problem? Please describe.**
I like to have wallpapers change once a day, for example, at midnight.
In order to do that, I have to go the app at that exact time, and do a manual change (untoggle and toggle back the selected wallpaper library) for that time to take place for the Next change. 

The issue comes when some day later I actually don't like the current wallpaper and I want to update the Library. I'll remove it from the Library, and refresh the toggle to change the current selection - the change time is reset to the current time.

**Describe the solution you'd like**
I'd like the ability to set a fixed time/periodicity for the Next changes. So that I can achieve what I've described: one wallpaper every day, at X time. And if I manually refresh the current wallpaper, I'd like to keep that same X time for the next change.

**Comment by Anthonyy232** [comment]
This is in progress (but not really, just started looking into it)

**Comment by Anthonyy232** [comment]
Hey, to clarify, you'd like the behavior to be 1, or 2? I'm thinking 1 makes more sense.

1. Change start time to ex: 00:00 and let time interval be one hour.  Start wallpaper changer -> Immediately change wallpaper -> Next wallpaper change at 01:00, then 02:00, , then 03:00, etc
2. Change start time to ex: 00:00 and let time interval be one hour.  Start wallpaper changer -> Immediately change wallpaper -> Next wallpaper change at 01:00, then 01:00 the next day, , then 01:00 two days after, etc.

**Comment by Wrakor** [comment]
> Hey, to clarify, you'd like the behavior to be 1, or 2? I'm thinking 1 makes more sense.
> 
> 1. Change start time to ex: 00:00 and let time interval be one hour.  Start wallpaper changer -> Immediately change wallpaper -> Next wallpaper change at 01:00, then 02:00, , then 03:00, etc
> 2. Change start time to ex: 00:00 and let time interval be one hour.  Start wallpaper changer -> Immediately change wallpaper -> Next wallpaper change at 01:00, then 01:00 the next day, , then 01:00 two days after, etc.

Yeah, 1 seems to make more sense for a one hour interval. 2 would be if the interval was one day.

**Comment by Anthonyy232** [comment]
Added in release v2.3.0
