### ISSUE TITLE
[Feature request] Disable paperize during certain hours

### ISSUE THREAD

**Issue by aRandomMenno** [Anthonyy232/Paperize#180]
## **Is your feature request related to a problem? Please describe.**
No the feature is not related to a problem, it is just a minor suggestion.

## **Describe the solution you'd like**
After choosing an album you can change many settings, so there I would like to so something so that you can disable the switching of the wallpapers on certain of the day example, during the night, when you're asleep.

## **Describe alternatives you've considered**
The above description is fine, I don't know how to explain it in other words.

## **Additional context**
Could not think of anything more.

**Comment by Anthonyy232** [comment]
I don't think I will be adding this since this is a pretty niche use -- but I am happy to reconsider in the future.
