### ISSUE TITLE
[Feature request]  Add event trigger to change wallpaper

### ISSUE THREAD

**Issue by M7amma** [Anthonyy232/Paperize#192]
I'm using Nova launcher which has the ability to make home screen swipes to trigger any action through events that implemented in apps. For Paperize, I want to change my wallpaper by manually swiping on home screen but this will require a trigger for 'wallpaper change event' to be set for this swipe. So can you please add it to the app?

**Comment by Anthonyy232** [comment]
I'm not really sure what you're talking about. Are you referencing adding support for this? 
https://novalauncher.com/sesame
