### ISSUE TITLE
[Bug] Changer activity service crashes

### ISSUE THREAD

**Issue by M7amma** [Anthonyy232/Paperize#196]
Hello & good day Mr. Anthony.

**Describe the bug**
While using the quick setting tile to change wallpaper, sometimes randomly the wallpaper stops changing and the background sticks on it's current wallpaper, and to make it work again,  I've to open Paperize and toggle the selected album, then the service starts to change the wallpaper again and work normally but after sometime the bug happens again. 
I've captured this log with an app called Logcat extreme (using internal option called per-app log) on play store and as it seems something happens I don't know what it is - and the service crashes or on loop (Sorry I don't understand the logcat parameters) but here's the screenshot anyway 
![Screenshot_20241015-104642_Logcat Extreme.png](https://github.com/user-attachments/assets/4290cb73-585d-4489-a21d-2e39a38007e2)

And I'm willing to provide you with any extra details or logs if you ask me.
Thanks a lot

**Comment by Anthonyy232** [comment]
Hi! So this occurs only if you use the quick tile button (relatively) quickly?

**Comment by M7amma** [comment]
> Hi! So this occurs only if you use the quick tile button (relatively) quickly?

Yes. This bug basically infects all the wallpaper changing triggers i.e quick setting tile and shortcut. I aslo don't know if this is caused from the app or another app or my rom behavior. Here's a clearer log screenshot ![Screenshot_20241015-111301_Logcat Extreme.png](https://github.com/user-attachments/assets/790ddf24-32da-4b18-aef4-c71ab9006707)

**Comment by M7amma** [comment]
> Is it cool if you send a video of it happening? Sorry about that.
Well that's fine and I'm willing to provide any extra investigations also. 

In that video ...

https://github.com/user-attachments/assets/865dce35-5df0-491e-8ba5-e52641d3393a


I'm trying the wallpaper changing by clicking on the qs tile and they change flawlessly until the bug comes up at 00:41 on this wallpaper : 

![kzcy506r7uid1](https://github.com/user-attachments/assets/e8fe1502-c741-4780-a247-327d9986a75f)

And I've to open Paperize and do some toggling in order to reset the app functionality and start working again.

**Comment by Anthonyy232** [comment]
I've been looking into this and there doesn't seem to be anything wrong logic wise. It might just be because of memory issues and race conditions of the service start/stopping and that, I can't do much about. I'll update if I figure out anything out, but yeah.

**Comment by M7amma** [comment]
Thanks for your efforts and I'll report this issue to the rom dev for fixing the possible memory leak issue.
