### ISSUE TITLE
[Feature request] Improving file selection

### ISSUE THREAD

**Issue by TCreopargh** [Anthonyy232/Paperize#206]
**Is your feature request related to a problem? Please describe.**

I have over 300 folders of wallpapers, and adding them one by one is quite repetitive. Due to this issue: https://github.com/Anthonyy232/Paperize/issues/205, I'm currently unable to import all of them. Although I know it's possible to add folders recursively by placing folders inside folders, this triggers a crash due to the aforementioned bug. Additionally, when trying to import many images at once, the app experiences a long black screen, and it’s generally more convenient and easier to organize when you add smaller folders individually.

Another minor issue is that the app uses the system file selector without offering an option to switch to gallery apps, which would be useful for quickly accessing newly saved images.

**Describe the solution you'd like**
1. A built-in file selector would be nice, which allows selecting multiple folders and even image cropping, like the one on de.j4velin.wallpaperChanger. 
2. Add a progressbar or just a spinning indicator when importing a lot of images, so the app doesn't turn black screen.

**Describe alternatives you've considered**

I understand that importing many folders at once may not be a common requirement for most users. If implementing a built-in file selector isn’t feasible, allowing the current system file selector to open other gallery apps could be a practical alternative (You can probably do this by adjusting the Intent parameters).

Thanks a lot for the great work! 👍🏻

**Comment by Anthonyy232** [comment]
Potentially-maybe on the progress bar/spinning indicator. I don't think I'll be implementing an in-house file selector because I think the current one is good enough

**Comment by Anthonyy232** [comment]
Added progress bar
