### ISSUE TITLE
Automatically changing theme colors

### ISSUE THREAD

**Issue by Zypher34** [Anthonyy232/Paperize#209]
I've set an albume for auto change, but every time it changes it also changes my theme colors. I tried setting colors on settings, but didn't work as it changed at next wallpaper. What should I do?

 - Device: RMX3710
 - Version 2.3.2

This is my first time submitting an issue, pardon me if I had made any mistakes.

**Comment by Anthonyy232** [comment]
Hi, this is not possible for me to fix. In fact, the app doesn't even touch your theme colors. It is all up to the implementation of whoever created your device (Samsung, Google, etc.) based on what they do when wallpaper changes. Sorry about that!
