### ISSUE TITLE
Blurry wallpaper when apply high resolution pictures

### ISSUE THREAD

**Issue by sakarie9** [Anthonyy232/Paperize#50]
The image becomes pixelated and blurry due to the loss of resolution when it is enlarged

For example it's a 4k picture and shouldn't be blurred like this

![Screenshot_20240725-094048_Yaap_Launcher](https://github.com/user-attachments/assets/0a1ccaa8-0236-4417-8e71-73393bc30073)

**Comment by Anthonyy232** [comment]
Can you provide that 4k image so I can do some testing? Or is it the one sent above?

**Comment by sakarie9** [comment]
> Can you provide that 4k image so I can do some testing? Or is it the one sent above?

I'm testing with this image [x.com](https://x.com/doganuraldesign/status/1814740642951528792)

**Comment by sakarie9** [comment]
> Also, would be great to know which scaling option is selected (fill, fit, stretch) and whether brightness or toggle sliders are on

fill, both brightness and blur toggle disabled

**Comment by Anthonyy232** [comment]
I'll check it out, thanks.

Would you be okay to download and install an APK update that I send here to check if the fix works? It'll be signed with the same keys as usual. Just want to make sure before creating another GitHub release, etc, etc

**Comment by sakarie9** [comment]
> Would you be okay to download and install an APK update that I send here to check if the fix works?

Sure

**Comment by Anthonyy232** [comment]
Let me know how this works for you. It looks good on my phone but my phone is only a FHD screen, and I don't have the best eye anyways.

If you downloaded from Play store, trying to update using the APK will say different signature (since that is signed by Google). Not sure why GitHub doesn't allow APK uploads so I've thrown it into a ZIP file, hope that's alright. Ignore the non-functional sync toggle, still a WIP. 

[app-release.zip](https://github.com/user-attachments/files/16369625/app-release.zip)

**Comment by sakarie9** [comment]
Looks good to me now!

**Comment by Anthonyy232** [comment]
Great! If you have any other 4k images, test them if you can and let me know if there is any of the same blurriness. Otherwise, I'll create a GitHub release and close this issue in a short bit.

**Comment by sakarie9** [comment]
Tested multiple 4k or higher images, all of them worked as expected.

During test, I realized that a "change to next wallpaper immediately" button might be useful. I will create a new issue for this feature request, as it is not related to the current issue.

Anyway, this issue is good to close

**Comment by Anthonyy232** [comment]
Fixed in commit https://github.com/Anthonyy232/Paperize/commit/4f7129f5f4db4341c2168c68e0cbf772884cb55e
