### ISSUE TITLE
IzzyOnDroid inclusion

### ISSUE THREAD

**Issue by shuvashish76** [Anthonyy232/Paperize#52]
I see your [F-Droid rfp](https://gitlab.com/fdroid/rfp/-/issues/2745) pending for a while.
Someone needs to create a merge request, maybe try it yourself : see https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md#merge-requests

For now I've requested for [IzzyOnDroid](https://apt.izzysoft.de/fdroid/) inclusion : https://gitlab.com/IzzyOnDroid/repo/-/issues/574

**Comment by Anthonyy232** [comment]
Hi! It actually just got merged today I think, and if I understand what they said correctly, it will take a few days to populate. I'm not too sure on how it works for F-Droid, but I believe that's what they said.
https://gitlab.com/fdroid/rfp/-/issues/2776

**Comment by shuvashish76** [comment]
> I'm not too sure on how it works for F-Droid, but I believe that's what they said.

https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client

**Comment by shuvashish76** [comment]
Welcome to F-Droid's official repository.

> Thanks for requesting the IzzyOnDroid one, I was actually thinking about it a while back.

Would you like me to close the IzzyOnDroid issue, or would you prefer to have it in both repositories?

**Comment by Anthonyy232** [comment]
I was thinking I could have it on both since some only use one or the other. Do you think that's fine?

**Comment by shuvashish76** [comment]
Umm...since it's reproducible on F-Droid cross updates possible with IzzyOnDroid.
It's totally upto you :)
[See here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ) if you want to weight the pros and cons.

**Comment by Anthonyy232** [comment]
Yeah, having it on both sounds good to me! Do I need to provide the APK each time or will it take the APK from F-Droid? I'm assuming the latter (which is good).

**Comment by shuvashish76** [comment]
F-Droid build from source and IzzyOnDroid pick the build provided by the app's dev. So yes you've to provide the APK on GitHub releases each/every time for IzzyOnDroid. Though it's has some more strong scanning mechanism than the official F-Droid repo itself. [^1] [^2]

> Yeah, having it on both sounds good to me!

Let's wait for @IzzySoft 's scanner report & his opinion on it.

[^1]: https://www.kuketz-blog.de/android-apps-auf-dem-seziertisch-eine-vertiefte-betrachtung/
[^2]: https://android.izzysoft.de/articles/named/iod-scan-apkchecks

**Comment by Anthonyy232** [comment]
Understood! That's fine too since GitHub is the first place I upload new releases anyways.

**Comment by IzzySoft** [comment]
Scanreport at IoD looks good. But as @shuvashish76 correctly reported, there are additional scans in place at IoD, so one thing missed at F-Droid is:

```
SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Quite easy to fix with a minor addition to your `build.gradle`, if you'd please do that for future releases:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

That said, Paperize will [become available at IzzyOnDroid](https://apt.izzysoft.de/packages/com.anthonyla.paperize) with the next sync around 6 pm UTC, so be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) for e.g. your Readme to link there :smiley:

Welcome aboard!

**Comment by IzzySoft** [comment]
PS, @shuvashish76 

> F-Droid build from source and IzzyOnDroid pick the APK provided by the app's dev.

In case of RB, F-Droid does pretty much the same as IoD: they ship the APK provided by the app's dev :stuck_out_tongue_winking_eye:

**Comment by shuvashish76** [comment]
> [I also want to keep it completely offline so I won't be providing any server-side wallpapers](https://www.reddit.com/r/androiddev/comments/1cnjqsq/paperize_wallpaper_changer/
).

@Anthonyy232 `android.permission.ACCESS_NETWORK_STATE` why this permission necessary ?

**Comment by Anthonyy232** [comment]
Um, I'm actually not sure. It's not declared in my app manifest. Could be a dependency, although I can't think of any that would require it either

**Comment by Anthonyy232** [comment]
Removed in latest commit
