### ISSUE TITLE
[Feature] Double tap to trigger wallpaper change 

### ISSUE THREAD

**Issue by Crazy-Unicooorn** [Anthonyy232/Paperize#53]
Coming from [Wallpaper changer](https://play.google.com/store/apps/details?id=de.j4velin.wallpaperChanger), we have more option that trigger a wallpaper change :

- On unlocking the phone
- Double tap on the homescreen

I would love to see these features here as well!

**Comment by Anthonyy232** [comment]
I could probably do the former relatively easily. 

I may be wrong, but generally there's no way to detect double tap on the home screen without using the live wallpaper approach (which personally I'm not a fan of because of the battery drain when I tried it) or actually being the launcher app itself. That was a long way of saying I'll look into it, but it very likely won't happen.

Thanks!

**Comment by shuvashish76** [comment]
Another idea could be : Use as "Assist app" (long press the home button of system navigation bar) to trigger random/up_next wallpaper change.
<details><summary>Details</summary>
<p>

![ResizedImage_2024-07-11_08-44-51_2061](https://github.com/MuntashirAkon/AppManager/assets/48226312/7bb1e386-0309-4eef-9149-9894b7015c69)

</p>
</details>

**Comment by Anthonyy232** [comment]
I'll look into it, haven't heard of that before. Do you know where to find documentation for it?

**Comment by shuvashish76** [comment]
It's usually present in your "Device settings > App & notification > Default apps > Assist & voice input > Assist app".
Sorry I'm not a developer, as a reference see how [this](https://github.com/rosenpin/Screenshot-Sharer) app works or take a look at the implication of from [this issue](https://github.com/cvzi/ScreenshotTile/issues/118).

**Comment by Anthonyy232** [comment]
Will do, thanks! If this doesn't require any overly invasive permissions and the play store allows me to do so, I'll probably add it.

**Comment by shuvashish76** [comment]
Looks like it requires [android.intent.action.ASSIST](url) action. Thanks for considering this feature.

**Comment by Crazy-Unicooorn** [comment]
I can confirm that the previous wallpaper changer I used is allowing the double tap by being a live wallpaper. 

They present it as an option like so:

![Screenshot_20240726_093810.jpg](https://github.com/user-attachments/assets/b4110f50-37a0-4d5d-972b-193ca0c88c24)

---

Since the nature of both way to trigger a wallpaper change is different, allow me to rename this issue, and open a new one mentioning this one !

**Comment by shuvashish76** [comment]
As we've shortcut for changing wallpaper #51 I'm not sure double tap, assist app & all these triggers are necessary.
- Assist app : You can change wallpaper while on any other app. But what's the point to view the wallpaper you've to come home screen anyway.
- Double Tap (live wallpaper mode) : Unnecessarily drains out battery.
- Double Tap (launcher app method) : I think launch apps use "Accessibility API" to do that. Honestly this [should only be used to assist users with disabilities](https://developer.android.com/reference/android/accessibilityservice/AccessibilityService). Though apps use this for various other features, many people considered it as "invasive permissions". Use it when it's absolutely necessary.

For all these triggers the user needs to perform the action from _home screen_ for which shortcut is more then enough IMO.

**Comment by Anthonyy232** [comment]
I agree. Keeping feature creep in mind and overall efficiency, I think I won't be adding double-tap to change wallpaper. Currently, tile and static app shortcut has been added to allow changing wallpaper. I may also add an option for pinned shortcuts for those who may find it useful. As discussed previously, I will add an option to change wallpaper on unlock/wake (https://github.com/Anthonyy232/Paperize/issues/55)

I'll be closing this!
