### ISSUE TITLE
[Feature] Unlock screen to trigger wallpaper change

### ISSUE THREAD

**Issue by Crazy-Unicooorn** [Anthonyy232/Paperize#55]
Opening this after discussing in #53 
This would be an option relatively easy to implement

**Comment by Anthonyy232** [comment]
Actually, I'm not sure if this is possible anymore. The two intent I would need is ACTION_USER_PRESENT and/or ACTION_USER_UNLOCKED, which seems to be restricted as of Android 8.0. I have to look into it more, but that's what I've got at the moment..

https://developer.android.com/develop/background-work/background-tasks/broadcasts/broadcast-exceptions

**Comment by Anthonyy232** [comment]
Won't be adding due to no possible efficient approach as far as I'm aware
