### ISSUE TITLE
Add Scroll bar view

### ISSUE THREAD

**Issue by shuvashish76** [Anthonyy232/Paperize#56]
Currently I've to scroll multiple times while viewing my wallpapers which is annoying.
Adding a scroll button would allow users to jump screen quickly.
Have a look on this [fastscroll](https://github.com/zhanghai/AndroidFastScroll) library.

**Comment by Anthonyy232** [comment]
I will look into this. Maybe I'll have a FAB that sends the user up to the top, can't imagine there is much of a need to fast scroll to other places -- but if I find an appropriate library then I'll consider it. fastscroll is for recycler view, which is an older Android style (XML), although I'm sure there are some for Compose as well.

**Comment by Anthonyy232** [comment]
Added in commit https://github.com/Anthonyy232/Paperize/commit/f9b6a96fc5d674f9390d36d1f0e7599b7a2b4585
