### ISSUE TITLE
Wallpaper select

### ISSUE THREAD

**Issue by uniquePWD** [Anthonyy232/Paperize#58]
Sometimes you want a specific wallpaper

**Comment by Anthonyy232** [comment]
This feature doesn't make a ton of sense to me. If you want to select a specific wallpaper, all you need to do is place the wallpaper in its own album.

**Comment by uniquePWD** [comment]
As a sports fan, I have lots of superstitions. One of which is that if my wallpaper matches the shirt of my team while they're playing, my team will win the match. Needless to say I have a full folder of team shirts. Fiddling around with albums seems excessive.

**Comment by Anthonyy232** [comment]
But in the case that you want to manually select your wallpaper, couldn't you just find it in the actual folder itself and change the wallpaper manually? I likely won't add this because I feel it isn't a good fit for this app -- which is an automatic changing album system.
