### ISSUE TITLE
Wallpaper search

### ISSUE THREAD

**Issue by uniquePWD** [Anthonyy232/Paperize#59]
As per #58 sometimes you want a specific wallpaper, but it's hard to find.

**Comment by Anthonyy232** [comment]
Can you expand where you would want to search for a specific wallpaper? I don't see this being used that often, but that's just with my use cases.

**Comment by uniquePWD** [comment]
As per #58, the ability to find all my Arsenal wallpapers and select one. Or if a new film is coming out and I want to represent as I'm meeting some friends before the cinema.

**Comment by Anthonyy232** [comment]
Unlikely to add for the same reasons mentioned in https://github.com/Anthonyy232/Paperize/issues/58
