### ISSUE TITLE
Paperize doesn't appear in system Wallpaper and Styles

### ISSUE THREAD

**Issue by uniquePWD** [Anthonyy232/Paperize#63]
It's missing.

**Comment by Anthonyy232** [comment]
![Screenshot_20240727_094645_Wallpaper and style](https://github.com/user-attachments/assets/a3961cb1-5986-4173-b1f8-63cefcc25965)

This wallpaper was set using the app. I'm not able to replicate this issue. What is your Android version, device model and/or OEM?

**Comment by uniquePWD** [comment]
What I m
![Screenshot_20240727-181933](https://github.com/user-attachments/assets/a0dc5bda-bdc2-4a54-b0af-ddf2d717b79f)
ean is here

**Comment by Anthonyy232** [comment]
Ah yes, an app only appears there if it's a live wallpaper app or manually added by the OEM. This isn't something I can change.
