### ISSUE TITLE
Custom wallpaper sorting and time triggers

### ISSUE THREAD

**Issue by MaximusPrimeForever** [Anthonyy232/Paperize#64]
Hi!
Came across your app on f-droid, and immediately installed. It's really polished, and does a great job! :)
I have 2 suggestions:
* The ability to custom sort wallpapers in each pack.  
The wallpapers will switch with a fixed interval like they do now.  
Maybe have it be a list with elements you can drag and sort in your liking. For example:
![custom_sort](https://github.com/user-attachments/assets/a244cfec-bc59-49f3-a92a-4944cc978e32)

* The ability to set a time trigger for each wallpaper in the pack, and they will change according to the device's clock.  
And have it look maybe something like:
![time_triggers](https://github.com/user-attachments/assets/fbffc071-d4bc-4aec-94d4-1535167e466b)

Thanks for making this app!

**Comment by Anthonyy232** [comment]
Hi! Thanks for suggesting these. I'm not sure if I'll add them as frankly I'm not too sure how I would incorporate them without doing a complete rewrite. I'll be closing this to prevent clutter.
