### ISSUE TITLE
Apply and change wallpaper for both screens (Foldables)

### ISSUE THREAD

**Issue by real-mizuya** [Anthonyy232/Paperize#65]
Hello, Foldables like the Samsung Galaxy Fold6 have 2 screens, one narrow cover screen and a squarish main screen. 

**I would love to apply the same wallpaper with the Paperize app for both screens.** Unfortunately they're not synced and there's (almost) always different wallpapers on each screen, even though I use the Paperize app on both screens. 

1. **Can you please make it possible to have the same wallpaper on both screens? **

2. **Also can you add a shortcut to quickly change the wallpaper on the fly?** I know there's a home screen Paperize app shortcut you recently added, but I can't use that with other apps like Tasker. 

3. **Can you also make it fill the screen on both screens?** It often fills the screen on the cover screen but doesn't fill it on the main screen. On the main screen uses "fit" instead of "fill". Once I change the wallpaper on the main screen, it uses "fill" there too. 

Thank you very much 😊

**Comment by Anthonyy232** [comment]
Hi, does Paperize not set at all for one of the screens? I'm not really sure how foldable works, but essentially, the only two flags provided to FLAG_SYSTEM and FLAG_LOCK. There doesn't seem to be any special flag that would hint at a third screen, so this may actually be an OEM issue. I'll try to look into it but I'm not sure at the moment.

Can you expand on what shortcut you mean?

**Comment by real-mizuya** [comment]
> Hi, does Paperize not set at all for one of the screens?

Foldables have 2 screens, for example the Fold6. I can set wallpapers for the lock screen and home screen for each screen. So there's:
- cover screen lock screen
- cover screen home screen 
- main screen lock screen 
- main screen home screen

When I set the wallpaper for the cover screen for lock and home screen it's just applied to those 2. When I unfold the device to the main screen, then there are different wallpapers. Even though I also set Paperize for lock and home screen, they use different wallpapers than on the cover screen.

> Can you expand on what shortcut you mean? 

Some apps have intents and shortcuts that aren't just accessible from the home screen app itself. Other apps like Tasker and KLWP/KWGT can access them to activate them from anywhere anytime or on specific triggers. 

For example here are some shown, when I select shortcuts from apps: 
![Screenshot_20240728_192757_Tasker.png](https://github.com/user-attachments/assets/d9f73598-706c-4751-ab9c-21d9bab28a19)

Paperize and some other apps aren't listed. 

In the end, it's not that important, but would be nice, if the user could change wallpaper anytime 😁

**Comment by Anthonyy232** [comment]
I don't know about the whole Tasker thing, but I'll do my best to find out and add it. 

For the foldables, I'd have to look into it a bit more but I can't guarantee anything. Looked through the API's source code and didn't really find anything relevant. Do you know any other open source wallpaper apps that works with your foldable?

**Comment by Anthonyy232** [comment]
Can I have you test setting the wallpaper using the schedule separately setting on and off? Would like to know if I could narrow it down to one or the either and get some insight.

**Comment by Anthonyy232** [comment]
Added tasker shortcut in commit https://github.com/Anthonyy232/Paperize/commit/064237bed4a46de5167d46714e85c1f398021edb

**Comment by Anthonyy232** [comment]
Closing for now, comment if someone has the same issue
