### ISSUE TITLE
Individual Library for Lock Screen and Home Screen

### ISSUE THREAD

**Issue by weiss1597** [Anthonyy232/Paperize#66]
A way to set Home Screen to use "Library A" and Lock Screen to use "Library B", each with it's different wallpapers inside.

That would make this app perfect for me, and on that note, I should say that this is an absolutely fantastic app, truly beautiful, solved all problems I've had with similar apps, went far beyond all of them, giving all I could want in such a simple manner, so far loved it!!

**Comment by Anthonyy232** [comment]
Thanks for the kind words. You mean a different album for lock and different album for home? I will probably add this at some point

**Comment by weiss1597** [comment]
Yes, exactly, so there will be one album just for Lock Screen and another different album for home screen

**Comment by Anthonyy232** [comment]
Added in commit https://github.com/Anthonyy232/Paperize/commit/f76313b99827eaa36fd72790ae0f22718bbfc554
Keep an eye out for version 2.0.0 update that will come out some time this month.. or next month..
