### ISSUE TITLE
Can't set the change interval lower then 15min

### ISSUE THREAD

**Issue by ReKylee** [Anthonyy232/Paperize#67]
Title says it all lol. I personally like when it changes frequently :>

**Comment by Anthonyy232** [comment]
What do you think is a good limit? I didn't think anyone would go below 15 so that's why that's there. Evidently not haha

**Comment by ReKylee** [comment]
I def get that! I'm one of those weirdos who like to change her wallpapers every minute or two, I think just not having a limit would be nice, and if someone wants 15 minutes they can set it just the same hehe

**Comment by Anthonyy232** [comment]
I will change it to one minute. This will be in a bigger update so don't expect it to be that soon, but I will definitely add it.

**Comment by Anthonyy232** [comment]
Fixed in commit https://github.com/Anthonyy232/Paperize/commit/f76313b99827eaa36fd72790ae0f22718bbfc554
