### ISSUE TITLE
[Bug] Certain images are stretched, even when "Fill" is selected

### ISSUE THREAD

**Issue by microbearsmb** [Anthonyy232/Paperize#71]
First off - thank you for this app, it looks awesome!

I have discovered what appears to be a bug: two of my 11 wallpapers are stretched, even though "Fill" is selected. The other 9 work just fine.

**Comment by Anthonyy232** [comment]
Hi! Can you upload the pictures here so I can test? If they're private pictures then can you tell me the image dimensions?

**Comment by microbearsmb** [comment]
![20220508_174103_HDR](https://github.com/user-attachments/assets/e772cc5b-0aac-4ffc-a9e3-c71d8eb45589)
![20210903_204930_HDR](https://github.com/user-attachments/assets/47e5e1cd-89b5-4038-87f3-4b7d5aed374d)
![20210403_192752_HDR](https://github.com/user-attachments/assets/5397c11a-15a2-4eff-bef8-af17813ad1fa)
![20240117_155621_HDR](https://github.com/user-attachments/assets/e047113f-7aec-4f6a-b3c2-8bb20a894e35)
![20221002_154628_HDR](https://github.com/user-attachments/assets/5b7b23b4-3f78-439d-8a56-ad4708f3f603)


Thank k you for the prompt reply! Here of 5 images: the bird, the flower, and the bookcase all get squished (turns out it was 3 that were affected). The lightbulb and the other one "Fill" just fine.

**Comment by Anthonyy232** [comment]
Fixed in commit https://github.com/Anthonyy232/Paperize/commit/b03e860dee1659857c7acd3d87d392691ce6e991
It was a one-liner multiplication instead of division mistake 😭

**Comment by microbearsmb** [comment]
Thank you so much! I will be more than willing to test once the fix is in an F-Droid build.

**Comment by Anthonyy232** [comment]
Fully fixed in commit https://github.com/Anthonyy232/Paperize/tree/2.0
