### ISSUE TITLE
some time it shows half wallpaper

### ISSUE THREAD

**Issue by iBabu007** [Anthonyy232/Paperize#90]
Please fixed this bug.
This happened when time interval set to 5 min otherwise it shows full wallpaper.
![Screenshot_20240727-073041](https://github.com/user-attachments/assets/7093204f-c44e-4b33-91da-8ad809d1dba8)
![Screenshot_20240810-195103](https://github.com/user-attachments/assets/2ca113c8-5288-4a95-ad25-a243ad0bb6b1)

**Comment by Anthonyy232** [comment]
Both, but mostly an Android issue. The app uses an Android service called WallpaperManager, which sometimes runs out of memory as it is applying the bitmap in most cases like this. This is pretty much unfixable on my end, and would require Android to increase the standard heap size and not be so aggressive with memory management.

**Comment by Anthonyy232** [comment]
I will still see if I can do something about it though. Would you mind providing those two exact wallpapers so I can test with as close conditions as possible?

**Comment by iBabu007** [comment]
![pexels-amol-mande-2683946](https://github.com/user-attachments/assets/d07a59ad-fd7b-4d0d-9c1d-3554315815f0)
![pexels-oidonnyboy-3375116](https://github.com/user-attachments/assets/41d81790-36a3-4d70-b41e-131ff9845a3c)

**Comment by Anthonyy232** [comment]
Thanks, I will update if there's anything, but expect nothing.
