### ISSUE TITLE
It is not running in the background

### ISSUE THREAD

**Issue by iBabu007** [Anthonyy232/Paperize#93]
It doesn't run in the background, but I removed this app from battery optimization, and it stopped after some time.

**Comment by Anthonyy232** [comment]
Can I get some more information?

Device and OS version
Interval
Anything specific that might've caused this (a restart?)

**Comment by iBabu007** [comment]
Device and OS version Stock Android 10
Interval  Interval not matter i set it 4 min & 5 min & 9 min.

Type (home or lock, scheduled separatlely, etc)  both are stopped

Anything specific that might've caused this (a restart?) No

**Comment by Anthonyy232** [comment]
What manufacturer? Or custom rom if you're using one

By type I mean which one is selected, is it supposed to change both off one album, both off two albums, home, lock etc

**Comment by iBabu007** [comment]
What manufacturer? 
Micromax
Or custom rom if you're using one
No

By type I mean which one is selected, is it supposed to change both off one album, both off two albums, home, lock etc
 both off one album

**Comment by Anthonyy232** [comment]
So you have home and lock enabled, but individual scheduling disabled?

**Comment by iBabu007** [comment]
So you have home and lock enabled, but individual scheduling disabled?
No
Individual scheduling enabled
For home screen 4 min
For Lock Screen 9 min

**Comment by Anthonyy232** [comment]
Okay, so individual scheduling with same album selected for both. How many items are in the album? All wallpapers, folders, or mix of both?

**Comment by iBabu007** [comment]
How many items are in the album? All wallpapers, folders, or mix of both?
27 items
All are wallpaper
No folder

**Comment by Anthonyy232** [comment]
I'm not able to replicate this on an Android 10 virtual emulator with the same settings. Can you try again? It might be an issue specific to your OEM. A screen recording of you going through a typical use of the app would be nice.

**Comment by iBabu007** [comment]
But slideshow app work well till now.

**Comment by Anthonyy232** [comment]
So if you try again, it doesn't work at all? I haven't been able to replicate this.
